---
language: node_js
node_js:
- '0.8'
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
  - secure: ! 'm3S80pTs02YwbGldUg+81CxQUCBbQp4o4DUlt/MJr3bDY+igqu3GDH/kZsOK

      QRxswPKmCtlqpS2SeggagmHmV0qThnpiaqZed3Eo2odwBZncE+IRG1xuFLKP

      RD+gS3Ujy6r1eSnlwuF4HyF9Xint2WKQ4EEn/wgSMDUn7ouWYmo='
  - secure: ! 'C7FfxSuR9bRzY6vQqq9px5F4LnS28y7v1SxRnj9vN0ll8ZPDmwP+4xavvTBs

      ENs7ez1l13DAK1P0141hGV0luk0Z5FMOk9o2d7JpqbiQw48Yu8O68NzsXmnk

      e/2LX2ZBEz94Gh+lRQRM+2pMwJAuYa0ogxPkDxGur0pJUp13gOc='
