language: node_js
node_js:
  - "0.8"
  - "0.10"
before_script:
  - npm install -g grunt-cli
  - nohup phantomjs --webdriver=4444 > /dev/null &
env:
  - [
      secure: "Xf3N2iXv8mm0kIfm4kMvipJhit6Ij0ivzl8Cs7zt6rKLvz4kgsm86ROHUrMn\nr/WWtV/5LWLRaCqo1fp1c3gVwlBfm2OaYcYYkxRcQyruWenKt0SVFwDTOcqn\nDUzZgKCNREJzHeg/ehN8lH3wI1LFsZ2TgLrBy/nmfIt9hAc4ozY=",
      secure: "MoxQjNsBFPbn2c75J2wUn/VUlW2I52GjqlXiCG34BDERRoM+mqJEMXMQg8xV\nLHieScVHGbk7MG6sGqIwknvhAgU/4DQBYCHAUzW3dtqCv3/FPQmP131vcrH1\nhyIjYUbM/J+S+Xsw2o/MnGf98Xza7x1RvnTBzAahkGTDR3kmxT0="
    ]

